# Common configuration for the mavel position controller

# Control
control_rate: 25.0
control_frame: "map"

# Path-following options
contrail:
  fallback_to_pose: true
  waypoint_hold_duration: 1.0
  waypoint_radius: 0.2
  waypoint_yaw_accuracy: 0.1
  spline_res_per_sec: 5

throttle:
  min: 0.0
  mid: 0.4715 #0.22
  max: 0.9

uav_mass: 2.035

# Maximum roll/pitch in radians
tilt_max: 0.39

# Emergency Landing Velocity (must be negative!)
failsafe_land_vel: -0.2

# Data Stream
min_rate:
  state:
    state: 0.2
    odometry: 10.0
  reference:
    triplet: 10.0

# PID Controllers
control:
  pos:
    x:
      p: 1.0
      i: 0.0
      d: 0.0
      min: -0.5
      max: 0.5
    y:
      p: 1.0
      i: 0.0
      d: 0.0
      min: -0.5
      max: 0.5
    z:
      p: 0.5
      i: 0.0
      d: 0.0
      min: -1.0
      max: 1.0
  vel:
    x:
      p: 3.0
      i: 0.1
      d: 0.5
      min: -2.5
      max: 2.5
    y:
      p: 3.0
      i: 0.1
      d: 0.5
      min: -2.5
      max: 2.5
    z:
      p: 5.0
      i: 0.5
      d: 1.0
      min: -2.5
      max: 5.0
